### ISSUE TITLE
Missing predefined macros

### ISSUE THREAD

**Issue by jyn514** [jyn514/saltwater#453]
[6.10.8.1 Mandatory macros](http://port70.net/~nsz/c/c11/n1570.html#6.10.8.1)

- [x] `__LINE__` - tricky, can't be passed through to `replace()` literally. This might be as simple as updating `self.definitions` whenever someone calls `line()`?
- [ ] `__COLUMN__` - tricky since we don't keep track of this explicitly and recalculate it. Probably needs yet more preprocessing before passing things through to `replace()`.
- [x] `__FILE__` - easy, but might need a refactor to put `PreProcessor` and `FileProcessor` back together.
- [x] `__DATE__` - easy, but needs a date-time dependency
- [x] `__TIME__` - same as `__DATE__`

[6.10.8.3 Conditional feature macros](http://port70.net/~nsz/c/c11/n1570.html#6.10.8.3)

- [ ] ` __STDC_IEC_559__ ` - trivial, good first issue. Code should go near https://github.com/jyn514/rcc/blob/180b27bb90bfcc02e2d4cba3afdd0a4dedccd662/src/lex/cpp.rs#L330.

Note that `__LINE__` should be the line at time of replacement, not within a definition. For example:
```c
$ clang -x c - -E -P
#define a __LINE__
a

2
```

**Comment by hdamron17** [comment]
Where is `__COLUMN__` described? I'm not seeing it in the standard.

**Comment by jyn514** [comment]
Huh, I can't remember where I got it from. It seems really niche even if it were a thing, I'm fine not implementing it.

**Comment by hdamron17** [comment]
I'm also not exactly sure what it would mean since `__COLUMN__` itself takes up 10 columns 😂

**Comment by hdamron17** [comment]
Can we close this since `__COLUMN__` is fake and `__STDC_IEC_559__` we can't guarantee?

**Comment by jyn514** [comment]
Yes we can!
