### ISSUE TITLE
Space between function macro name and args

### ISSUE THREAD

**Issue by hdamron17** [jyn514/saltwater#457]
Using `-E`

### Expected behavior
Function macro should be replaced when whitespace separates name and args. (this is true in `clang` at least)
```c

<a>
```

### Actual Behavior
Name is consumed but the macro is not replaced.
```c

 (a)
```

### Code
```c
#define f(a) <a>
f (a)
```

**Comment by hdamron17** [comment]
Didn't mean to add codegen label. Should be preprocessor, bug, and maybe good-first-issue.

**Comment by jyn514** [comment]
Looks like a regression from #437, this is working on 0.9.0.
