### ISSUE TITLE
Do not report type error when one type is "<type error>"

### ISSUE THREAD

**Issue by hdamron17** [jyn514/saltwater#458]
Since "\<type error\>" is a type generated only in the case of an already reported error, reporting it in a type error is redundant.

#### Code
```c
int main() {
  return ++i;
}
```

#### Expected Error (clang)
```
evil-test.c:2:12: error: use of undeclared identifier 'i'
  return ++i;
           ^
1 error generated.
```

#### Actual Error
```
evil-test.c:2:12 error: invalid program: use of undeclared identifier 'i'
  return ++i;
           ^
evil-test.c:2:10 error: invalid program: cannot assign to rvalue
  return ++i;
         ^^
evil-test.c:2:10 error: invalid program: cannot assign to rvalue
  return ++i;
         ^^
evil-test.c:2:10 error: invalid program: invalid operators for '+' (expected either arithmetic types or pointer operation, got '<type error> + <type error>'
  return ++i;
         ^^
4 errors generated
```

**Comment by jyn514** [comment]
This is pretty easy, just tedious. All the functions in https://github.com/jyn514/rcc/blob/master/src/analyze/expr.rs will have to be updated not to report an error if the expression has `Type::Error`.

Additionally, to fix the `cannot assign to rvalue` error, undeclared identifiers should be set as `lval`, not as `rval`: https://github.com/jyn514/rcc/blob/d17b79e37be581e8e424e3691dd7042c2d2b99c4/src/analyze/expr.rs#L228
