### ISSUE TITLE
Optional whitespace between command line argument key and value

### ISSUE THREAD

**Issue by hdamron17** [jyn514/saltwater#494]
This is blocked by [#19](https://github.com/RazrFalcon/pico-args/issues/19) on pico-args, but I wanted to make an issue here as well. It is common practice to leave off the space for `-I`, `-L`, and `-l` args, but currently we require a space. This will be needed for CMake compatibility as well, I think.

Expected
--------
`swcc -I/usr/local/include sample.c` successfully compiles sample.c using includes from `/usr/local/include`

Actual
------
The above command fails with message `swcc: error parsing args: unused arguments left: -I/usr/local/include`

**Comment by jyn514** [comment]
Sounds fine to me, but I suspect pico-args will say they don't want to implement it (they are *pico* after all :P) Our compile times are getting long enough that I'm fine switching to clap or gumdrop if it makes your life easier. I would prefer to avoid structopt because of the compile times.
